namespace OneShotMG.src.TWM
{
	public enum LaunchableWindowType
	{
		ONESHOT,
		PHOTO,
		DOCUMENT,
		JOURNAL,
		CUSTOMIZE,
		JUKEBOX,
		GALLERY,
		CONTACTS,
		ACHIEVEMENT,
		AUTHOR_PROFILE,
		NIKO_PROFILE,
		FROMNIKO_WALLPAPER,
		TUTORIAL_DELETE_FILE,
		TUTORIAL_INTRO_FILE,
		TUTORIAL_MOVE_FILE,
		DUMMY_FILE_FOR_TUTORIALS,
		DEBUG_CHEAT_APP,
		WALLPAPER,
		THEME,
		TIMER,
		CONTROLS,
		SHUTDOWN
	}
}
