namespace OneShotMG.src.TWM
{
	public enum TutorialStep
	{
		BEGIN,
		WAIT_FOR_HINTBOX_FADEOUT,
		PREAMBLE,
		MOVE_CURSOR,
		DRAG_FILE,
		LAUNCH_APPLICATION,
		MOVE_WINDOW,
		MINIMIZE_WINDOW,
		UNMINIMIZE_WINDOW,
		CLOSE_WINDOW,
		WRAP_UP,
		ONESHOT_APPEARS,
		COMPLETE,
		DELETE_CLICK_FILE,
		DELETE_CLICK_DELETE,
		DELETE_CONFIRM_DELETION,
		DELETE_CONGRATULATIONS,
		MOVEFILE_DRAG_FILE,
		MOVEFILE_DROP_FILE,
		MOVEFILE_CONGRATULATIONS,
		WAIT
	}
}
